[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/safefile"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.6.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[prune]
  go-tests = true
  unused-packages = true
