---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: changes

"on":
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run changelog
        id: changelog
        run: make changelog

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: CHANGELOG.md
          message: "docs: automated changelog update"
          push: true
          commit: --signoff

...
